-- creating a new column in the existing table
 ALTER TABLE EMPLOYEES ADD COLUMN Mentioned_Date DATE NULL;
 ALTER TABLE EMPLOYEES  ADD COLUMN Mentioned_TIME TIME NULL;

 ALTER TABLE EMPLOYEES ADD COLUMN Mentioned_Date DATE NULL, ADD COLUMN Mentioned_TIME TIME NULL, ADD COLUMN Mentioned_DateTime DATETIME NULL;